# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vladimir/Downloads/factor2_vhdl_test1_190421/factor2_vhdl_test1.srcs/sources_1/ip/fifo_4k/fifo_4k.xci
# IP: The module: 'fifo_4k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vladimir/Downloads/factor2_vhdl_test1_190421/factor2_vhdl_test1.srcs/sources_1/ip/fifo_4k/fifo_4k.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_4k'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/vladimir/Downloads/factor2_vhdl_test1_190421/factor2_vhdl_test1.srcs/sources_1/ip/fifo_4k/fifo_4k_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_4k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/vladimir/Downloads/factor2_vhdl_test1_190421/factor2_vhdl_test1.srcs/sources_1/ip/fifo_4k/fifo_4k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_4k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/vladimir/Downloads/factor2_vhdl_test1_190421/factor2_vhdl_test1.srcs/sources_1/ip/fifo_4k/fifo_4k.xci
# IP: The module: 'fifo_4k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vladimir/Downloads/factor2_vhdl_test1_190421/factor2_vhdl_test1.srcs/sources_1/ip/fifo_4k/fifo_4k.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_4k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/vladimir/Downloads/factor2_vhdl_test1_190421/factor2_vhdl_test1.srcs/sources_1/ip/fifo_4k/fifo_4k_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_4k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/vladimir/Downloads/factor2_vhdl_test1_190421/factor2_vhdl_test1.srcs/sources_1/ip/fifo_4k/fifo_4k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_4k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
