#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue May 04 18:56:14 MSK 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim factor_tb_behav -key {Behavioral:sim_1:Functional:factor_tb} -tclbatch factor_tb.tcl -view /home/master/Downloads/factor2_vhdl_test1_040521_1607/dds_tb_behav.wcfg -log simulate.log"
xsim factor_tb_behav -key {Behavioral:sim_1:Functional:factor_tb} -tclbatch factor_tb.tcl -view /home/master/Downloads/factor2_vhdl_test1_040521_1607/dds_tb_behav.wcfg -log simulate.log

