# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/master/factor2_vhdl_test1_030521_2102/factor2_vhdl_test1.srcs/sources_1/ip/fifo_1k/fifo_1k.xci
# IP: The module: 'fifo_1k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/master/factor2_vhdl_test1_030521_2102/factor2_vhdl_test1.srcs/sources_1/ip/fifo_1k/fifo_1k.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_1k'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/master/factor2_vhdl_test1_030521_2102/factor2_vhdl_test1.srcs/sources_1/ip/fifo_1k/fifo_1k_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_1k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/master/factor2_vhdl_test1_030521_2102/factor2_vhdl_test1.srcs/sources_1/ip/fifo_1k/fifo_1k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_1k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/master/factor2_vhdl_test1_030521_2102/factor2_vhdl_test1.srcs/sources_1/ip/fifo_1k/fifo_1k.xci
# IP: The module: 'fifo_1k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/master/factor2_vhdl_test1_030521_2102/factor2_vhdl_test1.srcs/sources_1/ip/fifo_1k/fifo_1k.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_1k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/master/factor2_vhdl_test1_030521_2102/factor2_vhdl_test1.srcs/sources_1/ip/fifo_1k/fifo_1k_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_1k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/master/factor2_vhdl_test1_030521_2102/factor2_vhdl_test1.srcs/sources_1/ip/fifo_1k/fifo_1k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_1k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
